name: Node setup
description: Setup Node
runs:
  using: composite
  steps:
    - name: 🚀 Starting Node setup
      shell: bash
      run: |
        echo -e "\033[32m----- setup Node started -----\033[0m"
        echo "START_TIME=$(date +%s)" >> $GITHUB_ENV
    - name: 📦 Install Node
      uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
      with:
        node-version: 24.21.0
        cache: npm
    - name: ✅ Finished Node setup
      shell: bash
      run: |
        END_TIME=$(date +%s)
        DURATION=$((END_TIME - START_TIME))
        echo -e "\033[32m----- setup Node finished in ${DURATION}s -----\033[0m"
