import { LayoutVariant } from '@redocly/config';

export const DEFAULT_LAYOUT = LayoutVariant.THREE_PANEL;


export const DEFAULT_MAX_DISPLAYED_ENUM_VALUES = 10;

export const DEFAULT_ROUTING_BASE_PATH = '';

export const GRAPHQL_DEFAULT_JSON_SAMPLES_DEPTH = 1;
export const ASYNCAPI_DEFAULT_JSON_SAMPLES_DEPTH = 3;
export const GRAPHQL_DEFAULT_SAMPLES_MAX_INLINE_ARGS = 2;
export const GRAPHQL_DEFAULT_FIELD_EXPAND_LEVEL = 4;

export const JSON_SAMPLES_EXPAND_LEVEL_DEFAULT = 2;
export const GENERATED_SAMPLES_MAX_DEPTH_DEFAULT = 8;

