extends: existence
message: 'Avoid using future tense: "%s". Use present tense instead.'
link: https://intranet.redoc.ly/contributing/documentation-style-guide/#tone-and-audience
ignorecase: true
level: error
raw:
  - "(going to( |\n|[[:punct:]])[a-zA-Z]*|"
  - "will( |\n|[[:punct:]])[a-zA-Z]*|"
  - "won't( |\n|[[:punct:]])[a-zA-Z]*|"
  - "[a-zA-Z]*'ll( |\n|[[:punct:]])[a-zA-Z]*)"
