 # Add security headers
 add_header 'X-Frame-Options' 'deny always' always;
 add_header 'X-XSS-Protection' '"1; mode=block" always' always;
 add_header 'X-Content-Type-Options' 'nosniff always' always;
 add_header 'Referrer-Policy' 'strict-origin-when-cross-origin' always;
 # Set access control header
 add_header 'Access-Control-Allow-Origin' '*' always;
 add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
 add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type' always; 