name: Publish cli

on:
  push:
    branches:
      - master


jobs:
  bundle:
    needs: [ check-version-cli ]
    if: needs.check-version-cli.outputs.changed == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          npm-${{ hashFiles('package-lock.json') }}
          npm-
    - run: npm ci
    - run: npm run bundle
    - name: Store bundle artifact
      uses: actions/upload-artifact@v2
      with:
        name: bundles-cli
        path: bundles
        retention-days: 1
  unit-tests:
    needs: [ check-version-cli ]
    if: needs.check-version-cli.outputs.changed == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm ci
    - run: npm test
  e2e-tests:
    needs: [ bundle ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm ci
    - name: Download bundled artifact
      uses: actions/download-artifact@v2
      with:
        name: bundles-cli
        path: bundles
    - run: npm run e2e
  bundle-cli:
    needs: [ check-version-cli ]
    if: needs.check-version-cli.outputs.changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-${{ hashFiles('package-lock.json') }}
            npm-
      - name: Install dependencies
        run: npm ci
      - name: Bundle
        run: npm run compile:cli
      - name: Store bundle artifact
        uses: actions/upload-artifact@v2
        with:
          name: cli
          path: cli
          retention-days: 1
  check-version-cli:
    name: Check Version
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.check.outputs.changed }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
      - name: Check if version has been updated
        id: check
        uses: EndBug/version-check@v2.0.1
        with:
          file-name: ./cli/package.json
          file-url: https://unpkg.com/redoc-cli/package.json
          static-checking: localIsNew
  publish-cli:
    needs: [bundle-cli, unit-tests, e2e-tests]
    if: needs.check-version-cli.outputs.changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
          registry-url: 'https://registry.npmjs.org'
      - uses: actions/checkout@v2
      - name: Download cli bundled artifact
        uses: actions/download-artifact@v2
        with:
          name: cli
          path: cli
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-${{ hashFiles('package-lock.json') }}
            npm-
      - name: Publish to NPM
        run: cd cli/ && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
