name: Sync Files
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Run GitHub File Sync
        uses: Redocly/repo-file-sync-action@master
        with:
          GH_PAT: ${{ secrets.GH_PAT }}
          COMMIT_PREFIX: "sync:"
          SKIP_PR: true
