name: Build with Webpack

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 16.x

    - name: Install
      run: npm install

    - name: Build
      run: npm run bundle:standalone

    - uses: actions/upload-artifact@v4
      with:
        path: |
          ./bundles
        retention-days: 1
